### ISSUE TITLE
Adding events.

### ISSUE THREAD

**Issue by Zackaryia** [UkoeHB/bevy_simplenet#2]
I am building a fairly drag and drop networking plugin on top of bevy_simplenet that is somewhat based on bevy_replicon. The addition basically just adds events so that a user can send events from the client to the server and vice versa. It makes the code much easier and simpler. Is this something that you would be interested in adding to bevy_simplenet? The code I am making can be found here: https://github.com/Zackaryia/SpaceRoyale/tree/main/src%2Fnetwork

Side note: the build on docs.rs is failing which is slightly annoying I think its because of the nightly toolchain, is this a priority fix or unfixable currently.

Thanks for the great project!

**Comment by UkoeHB** [comment]
> Side note: the build on docs.rs is failing which is slightly annoying I think its because of the nightly toolchain, is this a priority fix or unfixable currently.

@Zackaryia thanks for bringing this to my attention! It should be fixed in v0.5.1. EDIT: I just realized the fix is a breaking change since it updates the rust nightly version. If you have troubles, use `rustup update`.

> The addition basically just adds events so that a user can send events from the client to the server and vice versa. It makes the code much easier and simpler. Is this something that you would be interested in adding to bevy_simplenet? The code I am making can be found here: https://github.com/Zackaryia/SpaceRoyale/tree/main/src%2Fnetwork

This is very interesting! I think it would be quite nice to support bevy events as an alternative to the raw API. The approach you are taking seems promising (registering a [ channel : event type ] mapping and interfacing with the client/server in plugin-based systems), although I will need to take some time to consider it carefully.

An important feature of the raw API is the client and server output streams are synchronized with connection reports, whereas events are not synchronized since they need to be handled separately. In my own projects I handle client and server outputs synchronously in order to avoid thinking about race conditions: [for example](https://github.com/UkoeHB/bevy_girk_demo/blob/c45e8eda6228129b0943cb986d6b011a374125ce/libs/bevy_girk_demo_user_client/src/host_client/handle_host_incoming.rs#L44). Without stream synchronization, you need to think carefully about how to handle reconnects. What data needs to be sent by the server to reinitialize a reconnected client? Can anything go wrong if an event is handled out of order with a reconnect, due to cleanup procedures you run when you see a disconnect? Etc.

One question about your code: what is your use for replicon ticks? bevy_simplenet is `OrderedReliable`, which means message acking happens automatically behind the scenes, and the output streams are FIFO so you should not receive events out of order (assuming your server sends replication data before sending events in each tick).

**Comment by Zackaryia** [comment]
I am glad to have brought the docs.rs bug to your attention!

For the event ordering, I think it could be possible to make events synchronous maybe with a combination of scheduling, chaining, and some other shenanigans however that is a great point that I didn't consider. Even if synchronicity isn't possible adding event based messaging is very ergonomic in bevy and I think that justifies having to handle edge cases at least for me. With that being said paying attention to how to prevent race conditions is important and I haven't fully thought through how or if it is possible to do so (I am a bit of a bevy beginner still).

As for using replicon ticks, thanks for the catch. This was basically a copy paste from replicon that I was too tired to think through if I needed them, and I don't think I do haha.

**Comment by UkoeHB** [comment]
@Zackaryia Ok here's an idea for synchronizing events:
1) When polling for events in a tick, stop extracting events when you encounter a disconnect. Resume where you left off in the next tick.
2) Order event-handler systems like this: handle 'just connected', handle any special events sent on connect (e.g. the server might send an initialization package to the client when the client connects, and this will be the first event received by the client after each connect/reconnect), handle regular events, handle 'disconnected'.

This should ensure no events can leak past a disconnect, and no events can leak before a connect. It's possible for request errors to leak past a connect, but I think that should be ok for most use-cases.

**Comment by Zackaryia** [comment]
The easiest implimentation of this that I can think of would look like this.

The bevy_app would have a function (created via a trait) that would let you set a `.server_connected_system(System)` and a  `.server_disconnected_system(System)`   with simmilar client systems. Then this system will be triggered on client / server connect / disconnect.

This would allow us to immediately handle the connect / disconnect. I don't believe that this would solve all issues with ordering however it provides a good  starting point.

Any events queued to be sent before a disconnect however would be still queued to be sent after a reconnect so I am wondering what should be done about that? Do we let the user provided connect / disconnect system handle that or should we drain queued events on a disconnect / reconnect?

**Comment by UkoeHB** [comment]
> The bevy_app would have a function (created via a trait) that would let you set a .server_connected_system(System) and a .server_disconnected_system(System) with simmilar client systems. Then this system will be triggered on client / server connect / disconnect.

Even easier would be to simply recommend in the docs for people to organize their systems like that. Mandating systems in the API would probably be too restrictive.

> Any events queued to be sent before a disconnect however would be still queued to be sent after a reconnect so I am wondering what should be done about that? Do we let the user provided connect / disconnect system handle that or should we drain queued events on a disconnect / reconnect?

You made me realize the existing implementation also has this problem. A client (or server) can send a message after a reconnect but before the `Connected` event is handled. I have some thoughts on how to fix this, so that messages will fail to send until the `Connected` event for the current session has been consumed.

As far as bevy events, I'm not sure if there is an easy solution. We could maybe introduce a `SimplenetEventReader<T>` and `SimplenetEventWriter<T>` where the writer just sends an event immediately via the client/server API instead of queuing anything (to piggy-back off the API ordering guarantees, which need to be fixed as I mentioned). This might actually help with connect/disconnect ordering too, if we design the event reader to drop normal events if the disconnect event for those events' session has already been consumed.

**Comment by Zackaryia** [comment]
In this case I am not sure what your suggestions meant. 

> When polling for events in a tick, stop extracting events when you encounter a disconnect. Resume where you left off in the next tick.

Just to clarify as I understand it you mean stop polling events from the websocket that will be dispatched as Bevy Events when a disconnect is recieved (as a [server](https://github.com/Zackaryia/SpaceRoyale/blob/main/src/network/mod.rs#L118-L163) or a [client](https://github.com/Zackaryia/SpaceRoyale/blob/main/src/network/mod.rs#L165-L194)). I am not sure why this is done, is it because if a disconnect occurs then the WS (`Client<NetworkChannel>.next()` / `Server<NetworkChannel>.next()`) should return None already discontinuing iteration. This may be a misunderstanding on my part.

> Order event-handler systems like this: handle 'just connected', handle any special events sent on connect (e.g. the server might send an initialization package to the client when the client connects, and this will be the first event received by the client after each connect/reconnect), handle regular events, handle 'disconnected'.

I don't believe this is possible with Bevy Events which is why I suggested to have special systems that you pass in to be run when a connect / disconnect event as events are polled by a system and that system could be scheduled at any time. However what we could do is instead of using events we could maybe create a `instant_{client / server}_event` that has the following function signature.

```rust
fn instant_client_event<T: Event + Serialize + DeserializeOwned, Marker1>(&mut self, IntoSystemConfigs<Marker1>) -> &mut self
```

The idea of this is that it would call a system that gets instantly ran blockingly (so it blocks polling for events from the WebSocket) once an event is recieved rather than dispatching the event with `EventWritter`s. The only problem is that I am not sure how we would pass in the Event Data to the system however this seems like a issue that I just dont know bevy well enough to solve neatly.

This would pair nicely with the suggested `SimplenetEventWriter<T>` so that you can run systems that are able to send events as soon as you process a received event.

**Comment by UkoeHB** [comment]
> I am not sure why this is done, is it because if a disconnect occurs then the WS (Client<NetworkChannel>.next() / Server<NetworkChannel>.next()) should return None already discontinuing iteration. This may be a misunderstanding on my part.

The idea is to give the app a chance to consume the disconnect event before any post-reconnect events are emitted.

> I don't believe this is possible with Bevy Events which is why I suggested to have special systems that you pass in to be run when a connect / disconnect event as events are polled by a system and that system could be scheduled at any time.

Right, that's why the system ordering would be a recommendation to users. Not ideal, but maintains flexibility.

> The idea of this is that it would call a system that gets instantly ran blockingly (so it blocks polling for events from the WebSocket) once an event is recieved rather than dispatching the event with EventWritters. 

I like this idea, basically an injected event handler. We can either use an `In` param, or just use `SimplenetEventReader` in the handler to read event data.

**Comment by UkoeHB** [comment]
Implemented in https://github.com/UkoeHB/bevy_simplenet_events. @Zackaryia it would be great if you could integrate bevy_simplenet_events in your project and let me know how it goes.
